### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by CarlKCarlK**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Aha, very good @CarlKCarlK!

I think the simplest thing to do would be to open a new PR with the changes you made to the build.bat file, getting rid of the skip for windows and bumping the build number. Hopefully it'll all work ok then :crossed_fingers:

**Comment by CarlKCarlK** [comment]
I made the changes. The PR is being tested.
Dev by CarlKCarlK · Pull Request #13 · conda-forge/bed-reader-feedstock (github.com)<https://github.com/conda-forge/bed-reader-feedstock/pull/13/>

**Comment by jeromekelleher** [comment]
Hi @CarlKCarlK - I think it would be simpler to check out a fresh PR here rather that updating this one, as the history is a bit of a mess. This is one way to do it:

```
git fetch upstream
git checkout upstream/master
git checkout -b fix-windows
# apply changes
git push origin fix-windows
```
open a PR. Alternatively, the ``gh`` GitHub command like tool is excellent.

**Comment by CarlKCarlK** [comment]
Sounds good. I think I did it.
Fix windows by CarlKCarlK * Pull Request #14 * conda-forge/bed-reader-feedstock (github.com)<https://github.com/conda-forge/bed-reader-feedstock/pull/14/> is in testing

**Pull request closed without merging**
